version: '3.7'
services:
  jenkins-master:
    build: 
      context: .
      dockerfile: Dockerfile
    image: jenkins:latest
    volumes:
      - ./jenkins-master:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    ports:
      - 8080:8080
    restart: unless-stopped
    networks:
      - jenkins
    
networks:
  jenkins:
    driver: bridge
    name: jenkins
    external: true